language: php

matrix:
    include:
        - php: 7.0
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
    - composer self-update

install:
    - export SYMFONY_DEPRECATIONS_HELPER=strict
    - export COMPOSER_ROOT_VERSION=dev-master
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --verbose
